### PR TITLE
Closes #6, support gitignore files that have no ! lines

### LINKED ISSUE #6: Breaks on a very simple ignore file
If there are no 'negatives' in the `.gitignore` file it will then accept everything...

### PR DESCRIPTION
**Pull request by internalfx**

### CODE REVIEW

**Comment by phpnode** [comment]
@internalfx thanks!

**Comment by phpnode** [comment]
@internalfx added you as a collaborator

**Comment by internalfx** [comment]
Thank you. I noticed that the package on NPM is old. Any chance of an NPM publish?

**Comment by phpnode** [comment]
done, released 0.0.2

**Pull request merged**
